### ISSUE TITLE
Compilation & questions

### ISSUE THREAD

**Issue by Yomiquesh** [shmuelzon/esp32-ble2mqtt#103]
¿How can I solve this problem?

I'm using a raspi3, I installed esp-idf, and when I run the command _cmake ._ or _idf.py flash -p /dev/ttyS1_ this happens

![image](https://user-images.githubusercontent.com/74239953/114069527-619f8b80-989f-11eb-8ce3-e470c83658b4.png)

Another question:
The dev ttyS1 doesn't exists on my raspy, my ESP32 is in USB0, should I change the command for  _idf.py flash -p /dev/ttyUSB0_?

**Comment by shmuelzon** [comment]
Hey,

It seems that you don't have the toolchain installed or that your PATH isn't configured correctly. Did you run the install script in the ESP-IDF directory and also run the export script?

> should I change the command for idf.py flash -p /dev/ttyUSB0?

Yes, I think that should do it.

Let me know...
