### ISSUE TITLE
fatal error: eth_phy/phy.h: No such file or directory 

### ISSUE THREAD

**Issue by ZhidongYa** [shmuelzon/esp32-ble2mqtt#132]
**Question**
i run an old projekt with latest Version ESP-IDF, and then this problem comes. i find that the name of headfile has changed, so i change it into esp_wifi/include/phy.h, but this problem still here. why does it happen?

**Additional context**
![image](https://user-images.githubusercontent.com/93625836/139967757-6e1cb9f0-77c1-423f-a261-237380a1a2a2.png)

**Comment by shmuelzon** [comment]
Hey,

Things generally change between ESP-IDF versions. I suggest you use the ESP-IDF version specified in the README file.

**Comment by ZhidongYa** [comment]
thank you,

 @shmuelzon I have spend two hour to find the ESP-IDF version specified in the README file. but i still dont find it. Can you recommend one version or introduce the way to find the ESP-IDF version specified in the README file? By the way there is a requirement(cmake_minimum_required(VERSION 3.5)).

**Comment by shmuelzon** [comment]
![image](https://user-images.githubusercontent.com/2786045/140049012-d192d66d-e260-4111-b5c6-2a18197ad282.png)

**Comment by ZhidongYa** [comment]
Hey, @shmuelzon 
until now i have tried 3 kinds of version:v4.3.1 ; v4.3 ; v4.0.3. the problem is just same as before. i upload  this old projekt and you can find the reason with it. By the way this projekt was finished before October.2019 and there is no information about Version in README file. i will keep trying different Versions and later write  the result here.

[MyOldProjekt.zip](https://github.com/shmuelzon/esp32-ble2mqtt/files/7469302/MyOldProjekt.zip)

**Comment by shmuelzon** [comment]
I can't really help you with projects that I'm not related to in any way.
I suggest you try to contact whoever developed that application.
