### ISSUE TITLE
Unsubscribe from MQTT doesn't remove correct subscriptions

### ISSUE THREAD

**Issue by jumakki** [shmuelzon/esp32-ble2mqtt#148]
Hi, 
I found one issue when testing device which has a lot of characteristics and so a lot of MQTT subscriptions. ESP32 eventually ran out of memory after multiple reconnects.
https://github.com/shmuelzon/esp32-ble2mqtt/blob/774b516060e23b976e7bb194daea7bf5161ca15d/main/mqtt.c#L175-L189
Unsubscribe from MQTT doesn't remove correct subscriptions because of a typo
if (!strncmp...
on line 185 should be 
if (strncmp...
as continue is wanted when prefix doesn't match and strncmp return 0 when it matches

**Comment by shmuelzon** [comment]
Hey,

Thanks for that, I believe you're right.
Have you tried to modify it locally? Does it fix the memory issue you're seeing?

Thanks

**Comment by shmuelzon** [comment]
Great, thanks again for letting me know about this. I've already pushed the fix.
Any help, especially in the form of a pull request, is appreciated.
As for writing characteristics when connected, I haven't had the need for it yet, but it seems to me that publishing to the set topic of a characteristic with a retained flag once, would cause the ESP to write to that characteristics whenever it subscribes to that topic, which is right when the characteristic was discovered.
