### ISSUE TITLE
Ask for custom code/job

### ISSUE THREAD

**Issue by gavalierm** [shmuelzon/esp32-ble2mqtt#185]
**Question**
Hello, i found this lib and look so good to me. I m not C++ developer so write code in C++ is pain for me. Can we get in touch i want to ask you for help to write code which connect BT device (pre-defined service only) with passcode using mqtt as handshake handler (send request to mqtt and wait for pincode as response). 

After successfully  connection i want to read raw BT data and pass it to the mqtt to handle in node.js broker as "higher" logic.

I was very close with my private code, but i m strugling because i m not C++ developer and it takes ages to step forward.

You have ble.h maintained and looks works well. But is very complex for me. 

Can you helo?

Thank you!

**Comment by shmuelzon** [comment]
Hey,

As I barely have time to maintain my own projects, I can't really take on anything else.
Perhaps you'd have better luck at sites like https://bountysource.com.
