### ISSUE TITLE
mDNS (Bonjour) resolve support

### ISSUE THREAD

**Issue by robertcsakany** [shmuelzon/esp32-ble2mqtt#20]
By default all domain resolve (for example mqtt host) made by gethostbyname() . Which is using the given DNS servers only for resolve. But what if the MQTT / NTP servers doesn't registered in local DNS servers or there is no local DNS at all? On that case it is possible the services advertising themselves via multicast. 
Lot of arduino based firmwares tasmota/espurna supports that and workes well, in my network every IOT device and services are resolved with mDNS. I think with a host_resolver.c module can help to extend that functionality. I  know only mqtt service are bundled now, but for possible future implementation of remote log, ntp etc. can use that too. What do you think?

**Comment by shmuelzon** [comment]
The ESP-IDF implementation of mDNS seems pretty straight forward, however, the MQTT library doesn't support it.
This means that if we want to support mDNS queries, we will need to resolve the IP address before we pass it on to the MQTT library, and should probably be handled in mqtt.c.

The other component wrappers will manage mDNS as needed, i.e. wifi.c will register itself as a mDNS host, log.c will resolve by itself, etc.
Adding it to my list of enhancements...
