### ISSUE TITLE
BT_BTM: No random address yet, please set random address and try

### ISSUE THREAD

**Issue by typetrade** [shmuelzon/esp32-ble2mqtt#203]
*Please make sure you're using the ESP-IDF version specified in the [README](https://github.com/shmuelzon/esp32-ble2mqtt/blob/master/README.md) file, any other version is not supported.*

esp-idf-tools-setup-offline-5.2.1.exe

**Describe the bug**
edit \esp32-ble2mqtt\data\config.json
idf.py set-target esp32c3
idf.py build
idf.py -p COM3 flash monitor

I (666) Resolve: Initializing resolver
I (666) BLE_INIT: BT controller compile version [30b57c4]
I (676) BLE_INIT: Bluetooth MAC: 64:e8:33:8a:2d:16
I (686) phy_init: phy_version 1150,7c3c08f,Jan 24 2024,17:32:21
0x40380684: esp_restart_noos at D:/Espressif/521/frameworks/esp-idf-v5.2.1/components/esp_system/port/soc/esp32c3/system_internal.c:111

E (736) BT_BTM: No random address yet, please set random address and try

E (736) BT_APPL: bta_dm_ble_set_scan_fil_params(), fail to set scan params.
I (736) HTTPD: Initializing HTTP server

assert failed: xTaskCreatePinnedToCore freertos_tasks_c_additions.h:178 (( ( ( ( BaseType_t ) xCoreID ) >= 0 && ( ( BaseType_t ) xCoreID ) < 1 ) ? ( ( BaseType_t ) 1 ) : ( ( BaseType_t ) 0 ) ) == ( (
Stack dump detected
Core  0 register dump:
MEPC    : 0x40380698  RA      : 0x40388e18  SP      : 0x3fca5e20  GP      : 0x3fc94000
0x40380698: panic_abort at D:/Espressif/521/frameworks/esp-idf-v5.2.1/components/esp_system/panic.c:472
0x40388e18: __ubsan_include at D:/Espressif/521/frameworks/esp-idf-v5.2.1/components/esp_system/ubsan.c:313

TP      : 0x3fc5ea90  T0      : 0x37363534  T1      : 0x7271706f  T2      : 0x33323130
S0/FP   : 0x0000007e  S1      : 0x3fca6007  A0      : 0x3fca5e78  A1      : 0x3c1226fe
A2      : 0x0000007e  A3      : 0x00000028  A4      : 0x00000001  A5      : 0x3fc9f000
A6      : 0x7a797877  A7      : 0x76757473  S2      : 0x00000000  S3      : 0x3fca5e70
S4      : 0x3fca5e78  S5      : 0x00000000  S6      : 0x00000005  S7      : 0x00000000
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000
T3      : 0x6e6d6c6b  T4      : 0x6a696867  T5      : 0x66656463  T6      : 0x62613938
MSTATUS : 0x00001801  MTVEC   : 0x40380001  MCAUSE  : 0x00000007  MTVAL   : 0x00000000
0x40380001: _vector_table at ??:?

MHARTID : 0x00000000

Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\github\\esp32-ble2mqtt\\build\\ble2mqtt.elf', '-ex', 'target remote | "D:\\Espressif\\521\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\steve.TAO\\AppData\\Local\\Temp\\tmpnm2ohzt3"', '-ex', 'bt']' returned non-zero exit status 1.
b"error starting child process '| D:\\Espressif\\521\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\steve.TAO\\AppData\\Local\\Temp\\tmpnm2ohzt3': CreateProcess: No such file or directory\r\nNo stack.\r\n"

![20241007022346](https://github.com/user-attachments/assets/2bdb66b1-0f67-48d5-8186-ca42740f9694)

**To Reproduce**
1. git clone and cd
2. open ESP-IDF 5.2 PowerShell, and cd D:\github\esp32-ble2mqtt
3. edit \esp32-ble2mqtt\data\config.json
idf.py set-target esp32c3
idf.py build
idf.py -p COM3 flash monitor

**Expected behavior**
no error

**Configuration and logs**
{
  "network": {
    "wifi": {
      "ssid": "",
      "password": ""
    }
  },
  "mqtt": {
    "server": {
      "host": "",
      "port": 1883,
      "ssl": false,
      "username": "admin",
      "password": "123456",
      "client_id": "ble2mqtt"
    },
    "publish": {
      "qos": 1,
      "retain": true
    },
    "topics": {
      "prefix": "a/",
      "get_suffix": "/Get",
      "set_suffix": "/Set"
    }
  },
  "ble": {
    "whitelist": ["1c:70:c9:b1:16:6b","EB:69:FC:A9:EA:4D"],
    "services": {
      "definitions": {
        "0000ffe0-0000-1000-8000-00805f9b34fb": {
          "name": "Unknown Service"
        }
      },
      "whitelist": [
        "0000ffe0-0000-1000-8000-00805f9b34fb"
      ]
    },
    "characteristics": {
      "definitions": {
        "0000ffe4-0000-1000-8000-00805f9b34fb": {
          "name": "Unknown Characteristic",
          "types": ["uint8"]
        }
      },
      "whitelist": [
        "0000ffe4-0000-1000-8000-00805f9b34fb"
      ]
    }
  }
}

**Additional context**
Rebooting...
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0xc (RTC_SW_CPU_RST),boot:0xf (SPI_FAST_FLASH_BOOT)
Saved PC:0x40380684
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5820,len:0x1738
load:0x403cc710,len:0xb9c
load:0x403ce710,len:0x2e40
entry 0x403cc71a
I (24) boot: ESP-IDF v5.2.1-dirty 2nd stage bootloader
I (24) boot: compile time Oct  7 2024 02:02:01
I (24) boot: chip revision: v0.4
I (27) boot.esp32c3: SPI Speed      : 80MHz
I (32) boot.esp32c3: SPI Mode       : DIO
I (37) boot.esp32c3: SPI Flash Size : 4MB
I (42) boot: Enabling RNG early entropy source...
I (47) boot: Partition Table:
I (51) boot: ## Label            Usage          Type ST Offset   Length
I (58) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (65) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (73) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (80) boot:  3 ota_0            OTA app          00 10 00010000 00190000
I (88) boot:  4 ota_1            OTA app          00 11 001a0000 00190000
I (95) boot:  5 fs_0             Unknown data     01 82 00330000 00040000
I (103) boot:  6 fs_1             Unknown data     01 82 00370000 00040000
I (110) boot: End of partition table
I (114) esp_image: segment 0: paddr=00010020 vaddr=3c120020 size=48180h (295296) map
I (169) esp_image: segment 1: paddr=000581a8 vaddr=3fc93800 size=058b0h ( 22704) load
I (174) esp_image: segment 2: paddr=0005da60 vaddr=40380000 size=025b8h (  9656) load
I (177) esp_image: segment 3: paddr=00060020 vaddr=42000020 size=119b64h (1153892) map
I (364) esp_image: segment 4: paddr=00179b8c vaddr=403825b8 size=111e0h ( 70112) load
I (384) boot: Loaded app from partition at offset 0x10000
I (384) boot: Disabling RNG early entropy source...
I (396) cpu_start: Unicore app
I (404) cpu_start: Pro cpu start user code
I (404) cpu_start: cpu freq: 160000000 Hz
I (404) cpu_start: Application information:
I (407) cpu_start: Project name:     ble2mqtt
I (412) cpu_start: App version:      v0.18.0-1-g7bd29fe
I (418) cpu_start: Compile time:     Oct  7 2024 02:01:54
I (424) cpu_start: ELF file SHA256:  82a5d441e...
I (430) cpu_start: ESP-IDF:          v5.2.1-dirty
I (435) cpu_start: Min chip rev:     v0.3
I (440) cpu_start: Max chip rev:     v1.99
I (445) cpu_start: Chip rev:         v0.4
I (449) heap_init: Initializing. RAM available for dynamic allocation:
I (457) heap_init: At 3FCA2F70 len 0001D090 (116 KiB): RAM
I (463) heap_init: At 3FCC0000 len 0001C710 (113 KiB): Retention RAM
I (470) heap_init: At 3FCDC710 len 00002950 (10 KiB): Retention RAM
I (477) heap_init: At 50000010 len 00001FD8 (7 KiB): RTCRAM
I (484) spi_flash: detected chip: generic
I (488) spi_flash: flash io: dio
I (492) sleep: Configure to isolate all GPIO pins in sleep state
I (498) sleep: Enable automatic switching of GPIO sleep configuration
I (505) coexist: coex firmware version: 77cd7f8
I (511) coexist: coexist rom version 9387209
I (516) main_task: Started on CPU0
I (516) main_task: Calling app_main()
I (526) BLE2MQTT: Version: v0.18.0-1-g7bd29fe
I (526) Config: Initializing configuration
I (556) Config: version: 1b4c519dad071eb3c87033680574fe5c03c8a3d11265dcf201ac591b727caedd
I (556) Log: Initializing remote logging
I (566) OTA: Initializing OTA
I (566) pp: pp rom version: 9387209
I (566) net80211: net80211 rom version: 9387209
I (586) wifi:wifi driver task: 3fcadfc8, prio:23, stack:6656, core=0
I (586) wifi:wifi firmware version: a9f5b59
I (586) wifi:wifi certification version: v7.0
I (586) wifi:config NVS flash: enabled
I (596) wifi:config nano formating: disabled
I (596) wifi:Init data frame dynamic rx buffer num: 32
I (596) wifi:Init static rx mgmt buffer num: 5
I (606) wifi:Init management short buffer num: 32
I (606) wifi:Init dynamic tx buffer num: 32
I (616) wifi:Init static tx FG buffer num: 2
I (616) wifi:Init static rx buffer size: 1600
I (626) wifi:Init static rx buffer num: 10
I (626) wifi:Init dynamic rx buffer num: 32
I (626) wifi_init: rx ba win: 6
I (636) wifi_init: tcpip mbox: 32
I (636) wifi_init: udp mbox: 6
I (636) wifi_init: tcp mbox: 6
I (646) wifi_init: tcp tx win: 5760
I (646) wifi_init: tcp rx win: 5760
I (656) wifi_init: tcp mss: 1440
I (656) wifi_init: WiFi IRAM OP enabled
I (656) wifi_init: WiFi RX IRAM OP enabled
I (666) Resolve: Initializing resolver
I (666) BLE_INIT: BT controller compile version [30b57c4]
I (676) BLE_INIT: Bluetooth MAC: 64:e8:33:8a:2d:16
I (686) phy_init: phy_version 1150,7c3c08f,Jan 24 2024,17:32:21
0x40380684: esp_restart_noos at D:/Espressif/521/frameworks/esp-idf-v5.2.1/components/esp_system/port/soc/esp32c3/system_internal.c:111

E (736) BT_BTM: No random address yet, please set random address and try

E (736) BT_APPL: bta_dm_ble_set_scan_fil_params(), fail to set scan params.
I (736) HTTPD: Initializing HTTP server

assert failed: xTaskCreatePinnedToCore freertos_tasks_c_additions.h:178 (( ( ( ( BaseType_t ) xCoreID ) >= 0 && ( ( BaseType_t ) xCoreID ) < 1 ) ? ( ( BaseType_t ) 1 ) : ( ( BaseType_t ) 0 ) ) == ( (
Stack dump detected
Core  0 register dump:
MEPC    : 0x40380698  RA      : 0x40388e18  SP      : 0x3fca5e20  GP      : 0x3fc94000
0x40380698: panic_abort at D:/Espressif/521/frameworks/esp-idf-v5.2.1/components/esp_system/panic.c:472
0x40388e18: __ubsan_include at D:/Espressif/521/frameworks/esp-idf-v5.2.1/components/esp_system/ubsan.c:313

TP      : 0x3fc5ea90  T0      : 0x37363534  T1      : 0x7271706f  T2      : 0x33323130
S0/FP   : 0x0000007e  S1      : 0x3fca6007  A0      : 0x3fca5e78  A1      : 0x3c1226fe
A2      : 0x0000007e  A3      : 0x00000028  A4      : 0x00000001  A5      : 0x3fc9f000
A6      : 0x7a797877  A7      : 0x76757473  S2      : 0x00000000  S3      : 0x3fca5e70
S4      : 0x3fca5e78  S5      : 0x00000000  S6      : 0x00000005  S7      : 0x00000000
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000
T3      : 0x6e6d6c6b  T4      : 0x6a696867  T5      : 0x66656463  T6      : 0x62613938
MSTATUS : 0x00001801  MTVEC   : 0x40380001  MCAUSE  : 0x00000007  MTVAL   : 0x00000000
0x40380001: _vector_table at ??:?

MHARTID : 0x00000000

Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'D:\\Adrik\\github\\esp32-ble2mqtt\\build\\ble2mqtt.elf', '-ex', 'target remote | "D:\\Espressif\\521\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\steve.TAO\\AppData\\Local\\Temp\\tmpnm2ohzt3"', '-ex', 'bt']' returned non-zero exit status 1.
b"error starting child process '| D:\\Espressif\\521\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\steve.TAO\\AppData\\Local\\Temp\\tmpnm2ohzt3': CreateProcess: No such file or directory\r\nNo stack.\r\n"

Stack memory:
3fca5e20: 0x3fcc5fac 0x3fcc3fa8 0x3c14baa4 0x4038fc8c 0x00000000 0x3fc9f000 0x00060000 0x3c122680
3fca5e40: 0x00383731 0x00000010 0x00000000 0x00000000 0x00000000 0x3fc98298 0x3c14baa4 0x3fc9893c
3fca5e60: 0x3c122764 0x3fc982a8 0x3fca5e40 0x3fc982ac 0x3c122680 0x3fc98524 0x65737361 0x66207472
3fca5e80: 0x656c6961 0x78203a64 0x6b736154 0x61657243 0x69506574 0x64656e6e 0x6f436f54 0x66206572
3fca5ea0: 0x72656572 0x5f736f74 0x6b736174 0x5f635f73 0x69646461 0x6e6f6974 0x3a682e73 0x20383731
3fca5ec0: 0x28202828 0x28202820 0x73614220 0x70795465 0x20745f65 0x43782029 0x4965726f 0x20292044
3fca5ee0: 0x30203d3e 0x20262620 0x20282028 0x65736142 0x65707954 0x2920745f 0x6f437820 0x44496572
3fca5f00: 0x3c202920 0x29203120 0x28203f20 0x42202820 0x54657361 0x5f657079 0x20292074 0x20292031
3fca5f20: 0x2028203a 0x61422028 0x79546573 0x745f6570 0x30202920 0x29202920 0x203d3d20 0x00282028
3fca5f40: 0x00000000 0x00000000 0x3c124f7c 0x42008716 0x00001000 0x00000000 0x00000000 0x4038bf22
3fca5f60: 0x00000804 0x0000007c 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca5f80: 0x00000000 0x00000000 0x00000000 0x420089d6 0x3fca72dc 0x3fca5fd4 0x00000001 0x3fca5fbc
3fca5fa0: 0x3fca5fd4 0x00000000 0x3fca72dc 0x42118f3e 0x00000000 0x00000000 0x3fca3324 0x00000204
3fca5fc0: 0x3c121dd4 0x00000000 0x3c122000 0x42118f46 0x00000000 0x00001388 0x00000001 0x00000000
3fca5fe0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca6000: 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000150 0x3fca5da0 0x00000007
3fca6020: 0x3fc99268 0x3fc99268 0x3fca6018 0x3fc99260 0x00000018 0x3fcb4460 0x3fcb4460 0x3fca6018
3fca6040: 0x00000000 0x00000001 0x3fca5014 0x6e69616d 0x00000000 0x00000000 0x00000000 0x3fca6010
3fca6060: 0x00000001 0x00000000 0x3fcac598 0x420003d0 0x00000000 0x3fca3718 0x3fca3780 0x3fca37e8
3fca6080: 0x00000000 0x00000000 0x00000001 0x00000000 0x00000000 0x00000000 0x42003e9a 0x00000000
3fca60a0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca60c0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca60e0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca6100: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca6120: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca6140: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca6160: 0x00000000 0x00000000 0x00000600 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
3fca6180: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
3fca61a0: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
3fca61c0: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
3fca61e0: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
3fca6200: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5

ELF file SHA256: 82a5d441e

Rebooting...
ESP-ROM:esp32c3-api1-20210207

**Comment by shmuelzon** [comment]
Hey, I don't have a C3 on hand to test this but, from what I gather, this is probably related to the fact that it only has a single core. Can you please try the following changes at let me know if it makes any difference?
```patch
diff --git a/main/ble2mqtt.c b/main/ble2mqtt.c
index 4474575..7f299a9 100644
--- a/main/ble2mqtt.c
+++ b/main/ble2mqtt.c
@@ -705,7 +705,7 @@ static int start_ble2mqtt_task(void)
         return -1;
 
     if (xTaskCreatePinnedToCore(ble2mqtt_task, "ble2mqtt_task", 4096, NULL, 5,
-        NULL, 1) != pdPASS)
+        NULL, 0) != pdPASS)
     {
         return -1;
     }
diff --git a/main/ota.c b/main/ota.c
index a52b5ec..51e7c79 100644
--- a/main/ota.c
+++ b/main/ota.c
@@ -237,7 +237,7 @@ int ota_download(ota_type_t type, const char *url, ota_on_completed_cb_t cb)
     ctx->url = strdup(url);
     ctx->on_completed_cb = cb;
 
-    xTaskCreatePinnedToCore(ota_task, "ota_task", 8192, ctx, 5, NULL, 1);
+    xTaskCreatePinnedToCore(ota_task, "ota_task", 8192, ctx, 5, NULL, 0);
 
     return 0;
 }
```
