### ISSUE TITLE
BLE2MQTT-%02X%02X  AP not found

### ISSUE THREAD

**Issue by typetrade** [shmuelzon/esp32-ble2mqtt#204]
*Please make sure you're using the ESP-IDF version specified in the [README](https://github.com/shmuelzon/esp32-ble2mqtt/blob/master/README.md) file, any other version is not supported.*

only write flash, not use ESP-IDF.

**Describe the bug**

Download ble2mqtt-full.bin from https://github.com/shmuelzon/esp32-ble2mqtt/releases/tag/v0.18.0

PS D:\github> esptool.py -p COM3 -b 115200 --chip esp32 write_flash 0 ble2mqtt-full.bin
esptool.py v4.7.0
Serial port COM3
Connecting...

A fatal error occurred: This chip is ESP32-C3 not ESP32. Wrong --chip argument?
PS D:\github> esptool.py -p COM3 -b 115200 --chip esp32-C3 write_flash 0 ble2mqtt-full.bin
esptool.py v4.7.0
Serial port COM3
Connecting...
Chip is ESP32-C3 (QFN32) (revision v0.4)
Features: WiFi, BLE, Embedded Flash 4MB (XMC)
Crystal is 40MHz
MAC: 64:e8:33:8a:2d:14
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00000000 to 0x0038ffff...
Compressed 3735552 bytes to 951172...
Wrote 3735552 bytes (951172 compressed) at 0x00000000 in 22.5 seconds (effective 1329.3 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

and I can not see ap like BLE2MQTT-%02X%02X

**Comment by shmuelzon** [comment]
The images in the releases are for ESP32 only, not ESP32-C3 so it didn't even flash the chip:
```
A fatal error occurred: This chip is ESP32-C3 not ESP32. Wrong --chip argument?
```
I'll see if I can get around to building for other variants too
