### ISSUE TITLE
Build failing with syntax error

### ISSUE THREAD

**Issue by siehputz** [shmuelzon/esp32-ble2mqtt#25]
line 794 in main/ble.c is missing a semi-colon
ESP_ERROR_CHECK(esp_ble_gattc_register_callback(esp_gattc_cb))
should be
ESP_ERROR_CHECK(esp_ble_gattc_register_callback(esp_gattc_cb));

**Comment by shmuelzon** [comment]
Hey,

You're absolutely right! I wonder why I never got an error on that.
Anyways, thanks for pointing it out, it's fixed now.

Good day!
