### ISSUE TITLE
Is it possible compile by Mongoose-OS?

### ISSUE THREAD

**Issue by lourivalbarreto** [shmuelzon/esp32-ble2mqtt#36]
Hi,

First of all, congratulations for Ble2Mqtt bridge. Its really nice!

As I have others IoT firmwares using Mongoose-OS connected directly to AWS IoT Mqtt, I would like to know if is possible I compile your esp32-ble2mqtt firmware by Mongoose-OS and connect it to AWS IoT mqtt server?

Thanks a lot!
Jose Lima

**Comment by shmuelzon** [comment]
Hey Jose,

Thanks for the kind words.
From a quick look at Mongoose OS, I don’t think the code will run as is via Mongoose OS.
As for the second part, what’s stopping you from connecting this project to your AWS MQTT broker? Should be just a matter of configuration, no?

Good day

**Comment by lourivalbarreto** [comment]
I didn't try yet to connect it to AWS IoT.
But I really would like to compile it from Mongoose-OS to maintain my development pattern. Could you help me with this deal?

Thanks a lot!
Jose

**Comment by shmuelzon** [comment]
Hey Jose,

As far as I can tell, using Mongoose OS would be a complete rewrite of this project so it's not something I can help with.

Sorry
