### ISSUE TITLE
Incorrect behavior with CHAR_TYPE_FLOAT64

### ISSUE THREAD

**Issue by DurandA** [shmuelzon/esp32-ble2mqtt#4]
There is an incorrect behavior when the characteristic type is *float64*.

https://github.com/shmuelzon/esp32-ble2mqtt/blob/f478b2dbb7647e6f4b5a1b6faf3b3d427983c932/main/ble_utils.c#L365

Moreover, if the compiler use release (-0s) optimization level, the compilation fails:
```
/home/duranda/esp32-ble2mqtt/main/ble_utils.c:367:18: error: 'tmp.d' may be used uninitialized in this function [-Werror=maybe-uninitialized]
             p += sprintf(p, "%f,", tmp.d);
```

I think it could be fixed with something like this (not tested):
```
double tmp;
memcpy(&tmp, data + i, 8);

p += sprintf(p, "%f,", tmp);
```

**Comment by shmuelzon** [comment]
Thanks for opening this issue. It's fixed now.
