### ISSUE TITLE
error: 'sprintf' may write a terminating nul past the end of the destination [-Werror=format-overflow=]

### ISSUE THREAD

**Issue by nardev** [shmuelzon/esp32-ble2mqtt#41]
Hey guys, what did i do wrong here :D 

`/home/user/Desktop/esp32-ble2mqtt/main/config.c: In function 'config_log_port_get':
/home/user/Desktop/esp32-ble2mqtt/main/config.c:393:12: warning: returning 'void *' from a function with return type 'uint16_t' {aka 'short unsigned int'} makes integer from pointer without a cast [-Wint-conversion]
     return NULL;
            ^~~~
CC build/main/ota.o
CC build/main/wifi.o
CC build/main/ble2mqtt.o
CC build/main/broadcasters.o
/home/user/Desktop/esp32-ble2mqtt/main/broadcasters.c: In function 'ibeacon_metadata_get':
/home/user/Desktop/esp32-ble2mqtt/main/broadcasters.c:96:19: error: 'sprintf' may write a terminating nul past the end of the destination [-Werror=format-overflow=]
     sprintf(s, "%u", be16toh(beacon->major));
                   ^
/home/user/Desktop/esp32-ble2mqtt/main/broadcasters.c:96:5: note: 'sprintf' output between 2 and 6 bytes into a destination of size 5
     sprintf(s, "%u", be16toh(beacon->major));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/Desktop/esp32-ble2mqtt/main/broadcasters.c:98:19: error: 'sprintf' may write a terminating nul past the end of the destination [-Werror=format-overflow=]
     sprintf(s, "%u", be16toh(beacon->minor));
                   ^
/home/user/Desktop/esp32-ble2mqtt/main/broadcasters.c:98:5: note: 'sprintf' output between 2 and 6 bytes into a destination of size 5
     sprintf(s, "%u", be16toh(beacon->minor));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [/home/user/esp/esp-idf/make/component_wrapper.mk:292: broadcasters.o] Error 1
make: *** [/home/user/esp/esp-idf/make/project.mk:584: component-main-build] Error 2
`

**Comment by shmuelzon** [comment]
Hey,

Welcome!
Which ESP-IDF version are you using?

Thanks

**Comment by nardev** [comment]
Hello,

I think it's 3.2.2

**Comment by nardev** [comment]
p.s. why closing the issue?

**Comment by shmuelzon** [comment]
Because it should be fixed, at least the errors you posted.
Have you tried updating and trying again?

**Comment by nardev** [comment]
Thank you so much.

It builds now but i have another problem.

`AR build/xtensa/libxtensa.a
Generating esp32.project.ld
LD build/ble2mqtt.elf
esptool.py v2.7-dev
make: *** No targets specified and no makefile found.  Stop.
make: Entering directory /home/user/Desktop/esp32-ble2mqtt/mkspiffs make: Leaving directory /home/user/Desktop/esp32-ble2mqtt/mkspiffs
make: /home/user/Desktop/esp32-ble2mqtt/mkspiffs/mkspiffs: Command not found
make: *** [Makefile:34: /home/user/Desktop/esp32-ble2mqtt/build/spiffs.bin] Error 127
`

**Comment by shmuelzon** [comment]
Did you do a recursive clone of this repository? The `mkspiffs` directory is a git submodule and needs to be cloned as well.

**Comment by nardev** [comment]
ah.. :( sorry

**Comment by nardev** [comment]
Just did that, i hope the only difference from default configuration in menuconfig is maybe my USB port?

**Comment by nardev** [comment]
yeeeeeeeeeee

Thank You very much man!.

![Screenshot from 2019-08-06 10-38-47](https://user-images.githubusercontent.com/696054/62524729-6abc9780-b836-11e9-8ea2-d5aedb02563c.png)

**Comment by shmuelzon** [comment]
Cool, now let's hope that it runs correctly :)

**Comment by nardev** [comment]
It does.. send something to mqtt. Just bit too muchs encapsulated project for me. But great example for the task i'm about to do (i hope so).

thnx

**Comment by GOGYNAVA** [comment]
hola buenas, alguien me puede explicar que quiere decir este error?      'sprintf' may write a terminating nul past the end of the destination [-Wformat-overflow=]
   me a salido configurando un marlin para una sk4 1.4 turbo
