### ISSUE TITLE
MQTT server port cannot be changed

### ISSUE THREAD

**Issue by DurandA** [shmuelzon/esp32-ble2mqtt#5]
MQTT server port is always set to 1883 no matter the configuration: https://github.com/shmuelzon/esp32-ble2mqtt/blob/6c9ca943c06ac34db6e4316287e661a8caa43d37/main/config.c#L169

**Comment by DurandA** [comment]
That was quick!

**Comment by shmuelzon** [comment]
I aim to please :)
