### ISSUE TITLE
Pincode/passcode

### ISSUE THREAD

**Issue by GrumpyMeow** [shmuelzon/esp32-ble2mqtt#53]
In the readme i see the following:
```
"passkeys": {
  "aa:bb:cc:dd:ee:ff": 000000,
  "00:11:22:??:??:??": 123456
}
```
If i place this in the data/config.json file i get a json validation error.
Adding quotes seems to resolve the issue.
```
"passkeys": {
  "aa:bb:cc:dd:ee:ff": "000000",
  "00:11:22:??:??:??": "123456"
}
```

**Comment by shmuelzon** [comment]
Hey,

You're absolutely right! Apparently, leading zeros are considered as octal values but those are invalid in JSON, so leading zeros are considered invalid altogether.
You shouldn't use quotes as the code tries to read the passkey as a number.

I fixed the documentation.

Thanks!
