### ISSUE TITLE
ESP-IDF 4.1 Issues

### ISSUE THREAD

**Issue by jamesfcurran** [shmuelzon/esp32-ble2mqtt#75]
Cyclic reboot.   Last message is 

I (1658) coexist: [764729] Error! Should enable WiFi modem sleep when both WiFi and Bluetooth ar

I have tried to set every sleep-related setting for the radio:
```
egrep -i sleep\|modem sdkconfig
# CONFIG_BOOTLOADER_SKIP_VALIDATE_IN_DEEP_SLEEP is not set
# MODEM SLEEP Options
CONFIG_BTDM_MODEM_SLEEP=y
CONFIG_BTDM_MODEM_SLEEP_MODE_ORIG=y
# CONFIG_BTDM_MODEM_SLEEP_MODE_EVED is not set
# end of MODEM SLEEP Options
CONFIG_BTDM_BLE_SLEEP_CLOCK_ACCURACY_INDEX_EFF=1
CONFIG_ESP32_DEEP_SLEEP_WAKEUP_DELAY=2000
CONFIG_BTDM_CONTROLLER_MODEM_SLEEP=y
jim@marin:~/esp/esp32-ble2mqtt-esp-idf_v4.1_support$ 

```

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:6960
ho 0 tail 12 room 4
load:0x40078000,len:13720
ho 0 tail 12 room 4
load:0x40080400,len:3880
entry 0x40080680
I (32) boot: **ESP-IDF v4.1-rc** 2nd stage bootloader
I (32) boot: compile time 13:57:08
I (33) boot: chip revision: 1
I (36) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (54) boot.esp32: SPI Speed      : 40MHz
I (54) boot.esp32: SPI Mode       : DIO
I (54) boot.esp32: SPI Flash Size : 4MB
I (56) boot: Enabling RNG early entropy source...
I (62) boot: Partition Table:
I (65) boot: ## Label            Usage          Type ST Offset   Length
I (73) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (80) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (88) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (95) boot:  3 ota_0            OTA app          00 10 00010000 00180000
I (103) boot:  4 ota_1            OTA app          00 11 00190000 00180000
I (110) boot:  5 fs_0             Unknown data     01 82 00310000 00040000
I (118) boot:  6 fs_1             Unknown data     01 82 00350000 00040000
I (125) boot: End of partition table
I (130) boot_comm: chip revision: 1, min. application chip revision: 0
I (137) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x3bed0 (245456) map
I (238) esp_image: segment 1: paddr=0x0004bef8 vaddr=0x3ffbdb60 size=0x04120 ( 16672) load
I (245) esp_image: segment 2: paddr=0x00050020 vaddr=0x400d0020 size=0x106c70 (1076336) map
I (652) esp_image: segment 3: paddr=0x00156c98 vaddr=0x3ffc1c80 size=0x02454 (  9300) load
I (656) esp_image: segment 4: paddr=0x001590f4 vaddr=0x40080000 size=0x00400 (  1024) load
I (659) esp_image: segment 5: paddr=0x001594fc vaddr=0x40080400 size=0x1c8c4 (116932) load
I (734) boot: Loaded app from partition at offset 0x10000
I (734) boot: Disabling RNG early entropy source...
I (735) cpu_start: Pro cpu up.
I (738) cpu_start: Application information:
I (743) cpu_start: Project name:     ble2mqtt
I (748) cpu_start: App version:      1
I (753) cpu_start: Compile time:     Aug  8 2020 13:57:19
I (759) cpu_start: ELF file SHA256:  1b88d70120bc9bbb...
I (765) cpu_start: ESP-IDF:          v4.1-rc
I (770) cpu_start: Starting app cpu, entry point is 0x40081208
I (760) cpu_start: App cpu up.
I (780) heap_init: Initializing. RAM available for dynamic allocation:
I (787) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (793) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (799) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (805) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
I (811) heap_init: At 3FFD3760 len 0000C8A0 (50 KiB): DRAM
I (818) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (824) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (830) heap_init: At 4009CCC4 len 0000333C (12 KiB): IRAM
I (837) cpu_start: Pro cpu start user code
I (855) spi_flash: detected chip: generic
I (855) spi_flash: flash io: dio
I (856) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (928) BLE2MQTT: Version: 
I (938) Config: Initializing configuration
I (1038) Config: version: e81dccedae74638c16f694d2b76f180ee827a243175ae683d1fc1d6010ddbffd
I (1038) Log: Initializing remote logging
I (1038) OTA: Initializing OTA
I (1058) wifi:wifi driver task: 3ffd8e10, prio:23, stack:6656, core=0
I (1058) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (1058) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (1088) wifi:wifi firmware version: 3ea4c76
I (1088) wifi:config NVS flash: enabled
I (1088) wifi:config nano formating: disabled
I (1088) wifi:Init dynamic tx buffer num: 32
I (1098) wifi:Init data frame dynamic rx buffer num: 32
I (1098) wifi:Init management frame dynamic rx buffer num: 32
I (1108) wifi:Init management short buffer num: 32
I (1108) wifi:Init static rx buffer size: 1600
I (1118) wifi:Init static rx buffer num: 10
I (1118) wifi:Init dynamic rx buffer num: 32
I (1118) wifi:Set ps type: 0

I (1128) Resolve: Initializing resolver
I (1128) BTDM_INIT: BT controller compile version [219866f]
I (1138) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (1248) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0
D (1638) wifi:clear blacklist
I (1638) WiFi: Connecting to SSID IOT
**I (1658) coexist: [764729] Error! Should enable WiFi modem sleep when both WiFi and Bluetooth ar**
abort() was called at PC 0x400f3e86 on core 0

ELF file SHA256: 1b88d70120bc9bbb

Backtrace: 0x4008dbb9:0x3ffd8c10 0x4008df4d:0x3ffd8c30 0x400f3e86:0x3ffd8c50 0x400d2f50:0x3ffd8c70 0x400d31ad:0x3ffd8ca0 0x400ddf74:0x3ffd8cd0 0x400de03d:0x3ffd8cf0 0x400de2ce:0x3ffd8d100

Rebooting...
ets Jun  8 2016 00:22:57

**Comment by shmuelzon** [comment]
Hey,

This was fixed in 423bf18283ca5d5152c44c7ad716d00fd6417a15.
I'll let my test setup run for a few days to see how stable it is. If there won't be any special problems, support for v4.1 will be added to master when it's officially released.
Please let me know how it goes on your end.

Thanks
