### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by itProfi** [shmuelzon/esp32-ble2mqtt#9]
C:/msys32/home/User/esp/esp32-ble2mqtt/build/spiffs\libspiffs.a(spiffs_api.o):(.data.TAG+0x0): multiple definition of `TAG'
C:/msys32/home/User/esp/esp32-ble2mqtt/build/main\libmain.a(beacons.o):(.data.TAG+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [C:\msys32\home\User\esp\esp-idf/make/project.mk:407: /home/User/esp/esp32-ble2mqtt/build/ble2mqtt.elf] Ошибка 1

ESP-IDF ver 3.2-dev

What i do wrong?

**Comment by shmuelzon** [comment]
Hey,

Should be fixed now. Could you give it a try?
BTW - I highly suggest you not use ESP-IDF v3.2-dev but rather use the commit ID described in the README file. That one is, in my experience, more stable.

Good day
